//go:build windows

package localcommand

// AllowedCommands Windows 平台白名单
//
// 与 Linux 白名单不同：Windows 原生命令名、参数语法都不同，
// 下面用 Windows 等价命令重新组织，覆盖文件查看、网络、进程、服务、排障分析等场景。
var AllowedCommands = map[string]string{
	// ===== 文件与目录（CMD/PowerShell 通用） =====
	"dir":           "列出当前或指定目录下的文件与文件夹（替代 ls），只读查询",
	"ls":            "如果系统装了 Git/WSL 等，行为同 Unix ls；只读查询",
	"cat":           "在 PowerShell 中是 Get-Content 别名；读取文件内容，仅用于查看文本文件",
	"type":          "CMD 内置，显示文本文件内容（替代 cat），只读查询",
	"more":          "分页显示文本内容（CMD/PowerShell 内置），替代 less",
	"sort":          "按行排序文本内容（CMD 内置 + PowerShell Sort-Object）",
	"find":          "CMD 内置 find，在文件中搜索字符串（PowerShell 用 Select-String 替代）",
	"findstr":       "在文件中搜索字符串（替代 grep），日志/配置检索核心工具",
	"select-string": "PowerShell 内置，等价 grep，常用于日志检索",
	"copy":          "CMD 内置，复制文件/文件夹（替代 cp），仅限工作目录",
	"move":          "CMD 内置，移动/重命名文件（替代 mv），仅限工作目录",
	"ren":           "CMD 内置，重命名文件（替代 mv -r），仅限工作目录",
	"del":           "CMD 内置，删除文件；沙箱禁用，仅用于工作目录清理白名单项",
	"rd":            "CMD 内置，删除目录；同上，沙箱严格限制",
	"mkdir":         "创建空文件夹（CMD/PowerShell 都支持），仅允许沙箱工作目录",
	"rmdir":         "删除空目录；同上，沙箱严格限制",
	"pushd":         "切换到指定目录并压栈（CMD 内置）",
	"popd":          "返回 pushd 之前的目录（CMD 内置）",
	"cd":            "切换当前目录",
	"chdir":         "CMD 内置，等价 cd",
	"pwd":           "在 PowerShell 中等价 Get-Location；显示当前路径",
	"tree":          "树形递归打印目录层级（CMD 内置），只读",
	"fc":            "CMD 内置，对比两个文件差异（替代 diff）",

	// ===== 文本处理 =====
	"head":           "PowerShell Get-Content -Head N；读取文件前 N 行",
	"tail":           "PowerShell Get-Content -Tail N；读取文件末尾 N 行",
	"wc":             "PowerShell (Get-Content).Count；统计行数",
	"echo":           "CMD/PowerShell 都支持，打印文本（替代 echo）",
	"write-output":   "PowerShell 内置，打印文本",
	"set":            "CMD 内置，列出/设置环境变量",
	"$env":           "PowerShell 内置，访问环境变量",
	"measure-object": "PowerShell 内置，统计文本行/词/字符（替代 wc）",
	"compare-object": "PowerShell 内置，对比对象/文件（替代 diff）",
	"sort-object":    "PowerShell 内置，按字段排序",
	"select-object":  "PowerShell 内置，按列提取（替代 cut）",
	"where-object":   "PowerShell 内置，按条件过滤（替代 grep）",
	"format-table":   "PowerShell 内置，格式化表格输出",
	"format-list":    "PowerShell 内置，格式化列表输出",
	"out-file":       "PowerShell 内置，写入文件（替代 > 重定向）",
	"tee-object":     "PowerShell 内置，同时输出到屏幕和文件（替代 tee）",
	"get-content":    "PowerShell 内置，读取文件（替代 cat）",
	"get-filehash":   "PowerShell 内置，计算文件哈希（替代 md5sum/sha256sum）",
	"get-unique":     "PowerShell 内置，去除连续重复行（替代 uniq）",

	// ===== 基础信息 =====
	"hostname":       "显示本机主机名（CMD/PowerShell 内置）",
	"whoami":         "显示当前登录用户（CMD/PowerShell 内置）",
	"whoami /priv":   "查看当前用户权限",
	"whoami /groups": "查看当前用户所属组",
	"ver":            "CMD 内置，显示 Windows 版本（替代 uname）",
	"systeminfo":     "CMD 内置，显示完整系统信息（CPU/内存/OS/补丁），替代 uname/lscpu/dmidecode",
	"date":           "CMD/PowerShell 内置，显示/设置日期",
	"time":           "CMD/PowerShell 内置，显示/设置时间",
	"echo %date%":    "CMD 显示日期变量",
	"echo %time%":    "CMD 显示时间变量",

	// ===== 进程与服务 =====
	"tasklist":      "CMD 内置，列出进程（替代 ps），含 PID/会话/内存",
	"tasklist /v":   "详细进程列表",
	"tasklist /m":   "显示每个进程加载的 DLL（替代 lsof 部分）",
	"tasklist /svc": "显示进程承载的服务（替代 supervisorctl status）",
	"taskkill":      "CMD 内置，按 PID/名称结束进程（替代 kill/pkill）",
	"get-process":   "PowerShell 内置，列出进程（替代 ps），支持按 CPU/内存排序",
	"stop-process":  "PowerShell 内置，结束进程（替代 kill）",
	"get-service":   "PowerShell 内置，列出 Windows 服务（替代 systemctl）",
	"start-service": "PowerShell 内置，启动服务；沙箱内禁止变更，保留为可读",
	"stop-service":  "PowerShell 内置，停止服务；同上",
	"sc query":      "CMD 内置，查询服务状态（替代 systemctl status）",
	"sc qc":         "CMD 内置，查询服务配置",

	// ===== 网络诊断 =====
	"ipconfig":                 "CMD 内置，显示本机 IP/DNS/网关（替代 ifconfig/ip addr）",
	"ipconfig /all":            "显示完整网络配置（含 DNS、DHCP、MAC）",
	"ipconfig /displaydns":     "显示 DNS 缓存",
	"ipconfig /flushdns":       "清空 DNS 缓存；变更操作，沙箱禁止",
	"get-netipaddress":         "PowerShell 内置，等价 ipconfig（新版）",
	"get-netadapter":           "PowerShell 内置，查看网卡硬件状态（替代 ethtool）",
	"get-netroute":             "PowerShell 内置，查看路由表（替代 ip route / route）",
	"get-netconnectionprofile": "PowerShell 内置，查看网络连接配置",
	"ping":                     "CMD/PowerShell 内置，ICMP 连通性探测",
	"tracert":                  "CMD 内置，路由追踪（替代 traceroute）",
	"pathping":                 "CMD 内置，ping+tracert 组合（替代 mtr）",
	"netstat":                  "CMD 内置，列出端口/连接/路由（替代 ss）",
	"netstat -ano":             "按 PID 列出端口占用（替代 lsof -i）",
	"get-nettcpconnection":     "PowerShell 内置，列出 TCP 连接（替代 ss -t）",
	"nslookup":                 "CMD/PowerShell 内置，DNS 解析查询",
	"Resolve-DnsName":          "PowerShell 内置，DNS 解析（替代 dig）",
	"arp":                      "CMD 内置，查看 ARP 缓存（替代 arp/ip neigh）",
	"get-arp":                  "PowerShell 内置，ARP 表",
	"route print":              "CMD 内置，查看路由表（替代 ip route）",
	"netsh":                    "CMD 内置，Windows 网络配置；仅允许 advfirewall/show 等只读子命令",
	"netsh advfirewall show":   "查看 Windows 防火墙规则（替代 iptables -L）",
	"test-netconnection":       "PowerShell 内置，TCP 端口连通性探测（替代 telnet/nc -zv）",
	"curl":                     "Windows 10+ 自带，HTTP 调试；仅 GET 只读查询",
	"wget":                     "需额外安装；与 Linux 一致，仅 GET 下载",
	"winrm":                    "Windows 远程管理；仅允许查询，禁止配置变更",

	// ===== 性能与故障分析（主机排障核心） =====
	"typeperf":         "CMD 内置，实时采样性能计数器（替代 sar/iostat/vmstat），输出 CSV",
	"perfmon":          "图形化性能监视器（替代 glances）",
	"perfmon /report":  "生成系统性能诊断报告（替代 atop 历史回放）",
	"wmic":             "WMI 命令行（已弃用但仍可用），替代 iostat/vmstat 等",
	"wmic cpu":         "查看 CPU 详细信息（替代 lscpu）",
	"wmic memorychip":  "查看内存条信息（替代 lsmem）",
	"wmic diskdrive":   "查看磁盘信息（替代 lsblk）",
	"wmic logicaldisk": "查看逻辑分区（替代 df）",
	"wmic process":     "查看进程（替代 ps，tasklist 更推荐）",
	"wmic service":     "查看服务（替代 systemctl list-units）",
	"wmic nic":         "查看网卡（替代 ip a）",
	"wmic os":          "查看操作系统信息（替代 uname）",
	"get-counter":      "PowerShell 内置，实时/采样性能计数器（替代 sar/vmstat），最强大",
	"get-wmiobject":    "PowerShell 内置，WMI 查询（替代 wmic，新版推荐）",
	"get-ciminstance":  "PowerShell 内置，CIM 查询（替代 wmic，推荐）",
	"get-eventlog":     "PowerShell 内置，读取事件日志（替代 journalctl/dmesg）",
	"get-winevent":     "PowerShell 内置，新版事件日志（替代 journalctl）",
	"wevtutil":         "CMD 内置，事件日志查询（替代 journalctl）",
	"wevtutil qe":      "查询指定日志",

	// ===== 日志与故障现场 =====
	"eventvwr":         "图形化事件查看器（替代 journalctl GUI）",
	"quser":            "CMD 内置，查询当前登录用户（替代 who/w）",
	"qwinsta":          "CMD 内置，列出登录会话",
	"query session":    "CMD 内置，列出远程会话",
	"query user":       "CMD 内置，列出用户",
	"query process":    "CMD 内置，列出进程（替代 ps）",
	"query termserver": "CMD 内置，查询终端服务",
	"get-wmiobject -class win32_logonsession": "PowerShell 查询登录会话（替代 last）",
	"get-eventlog -logname security":          "PowerShell 查询安全日志（替代 lastb / auth.log）",
	"get-winevent -logname application":       "查询应用日志",
	"get-winevent -logname system":            "查询系统日志（替代 dmesg）",

	// ===== 磁盘与硬件 =====
	"chkdsk":           "CMD 内置，检查磁盘错误（需只读 /scan 模式，禁写操作）",
	"defrag":           "CMD 内置，磁盘碎片整理；变更操作，沙箱禁止",
	"diskpart":         "CMD 内置，分区管理；高危，沙箱严格禁用",
	"fsutil":           "CMD 内置，文件系统工具；仅 fsinfo/fsquery 等只读子命令",
	"fsutil fsinfo":    "查看卷信息（替代 df）",
	"get-volume":       "PowerShell 内置，查看卷信息（替代 df）",
	"get-physicaldisk": "PowerShell 内置，查看物理磁盘（替代 lsblk/smartctl）",
	"get-disk":         "PowerShell 内置，查看磁盘",
	"get-partition":    "PowerShell 内置，查看分区",
	"driverquery":      "CMD 内置，列出已安装驱动（替代 lsmod/lspci 部分）",
	"get-pnpdevice":    "PowerShell 内置，列出 PNP 设备（替代 lspci/lsusb）",
	"pnputil":          "CMD 内置，驱动包管理；仅枚举（/enum-drivers），禁止安装/删除",

	// ===== 软件包与运行时 =====
	"get-command":     "PowerShell 内置，列出可用命令（替代 which/type）",
	"get-module":      "PowerShell 内置，列出已加载模块",
	"get-package":     "PowerShell 内置，列出已安装包（替代 rpm/dpkg）",
	"get-appxpackage": "PowerShell 内置，列出应用商店应用",
	"winget":          "Windows 包管理器；仅 list/search/show，禁止 install/upgrade",
	"choco":           "Chocolatey 包管理器；仅 list/search/info，禁止 install/upgrade",
	"scoop":           "Scoop 包管理器；仅 list/search/info",
	"where":           "CMD 内置，定位可执行文件路径（替代 which）",
	"help":            "CMD/PowerShell 内置，命令帮助（替代 man）",
	"get-help":        "PowerShell 内置，详细帮助",

	// --- Python / Node / 通用脚本运行时 ---
	"python":  "Python 解释器入口（2.x/3.x，-c/-m/-V/-h 等），仅限工作目录；禁止 -c 执行远程代码",
	"python3": "Python 3 解释器入口（-c/-m/-V/-h 等），仅限工作目录；禁止 -c 执行远程代码",
	"py":      "Windows Python Launcher（按指定版本号启动已安装的 Python，如 py -3），仅限工作目录",
	"pip":     "pip 包管理器（仅 list/show/check/freeze 等只读查询），禁止 install/uninstall",
	"pip3":    "pip3 包管理器（仅 list/show/check/freeze 等只读查询），禁止 install/uninstall",
	"node":    "Node.js 运行时（-v/-e/-p 等），仅限工作目录，禁止 -e 执行远程代码",
	"npm":     "npm 包管理器（仅 list/view/ls/--version/audit/outdated），禁止 install/uninstall/update/run",

	// --- 外部 AI CLI 桥接 ---
	// Anthropic Claude Code CLI（外部程序，通过 local_command 调用）。
	// 仅暴露顶层命令名，参数级别的安全由 localcommand 软禁止 + 白名单兜底。
	"claude-code": "Anthropic Claude Code CLI（query/task/docs/info 子命令），调用主机上的 claude-code 程序完成 Claude Code 官方文档查询与编码任务分发；禁止参数中携带 Authorization/Cookie/API Key 等敏感凭据，禁止走 --data/-F/-T 等敏感体上传",

	// ===== 防火墙与安全 =====
	"netsh advfirewall show allprofiles": "查看所有防火墙 profile 状态",
	"get-netfirewallrule":                "PowerShell 内置，查看防火墙规则（替代 iptables -L）",
	"get-netfirewallprofile":             "PowerShell 内置，查看防火墙 profile",
	"get-mpcomputerstatus":               "查看 Defender 状态",
	"get-bitlockervolume":                "查看 BitLocker 加密状态（仅查看）",

	// ===== 网络抓包（需管理员安装 Npcap 等） =====
	"netsh trace":              "Windows 自带抓包工具（替代 tcpdump），start/stop 沙箱内可用",
	"netsh trace start":        "开启网络追踪（替代 tcpdump -i any）",
	"netsh trace stop":         "停止追踪并生成 ETL 报告",
	"pktmon":                   "Windows 10+ 内置包监控（替代 tcpdump），高级诊断",
	"Get-NetAdapterStatistics": "PowerShell 内置，按网卡统计收发包/错包",

	// ===== 文件搜索与统计 =====
	"get-childitem":                      "PowerShell 内置，列出文件（替代 ls/dir）",
	"gci":                                "get-childitem 别名",
	"where-object {$_.Length -gt 100MB}": "PowerShell 查找大文件（替代 find -size）",
	"get-item":                           "PowerShell 内置，查看文件元信息（替代 stat）",
	"get-acl":                            "PowerShell 内置，查看文件 ACL（替代 stat 权限部分）",
	"test-path":                          "PowerShell 内置，检查路径是否存在",
	"resolve-path":                       "PowerShell 内置，解析路径（替代 realpath）",
	"convert-path":                       "PowerShell 内置，转换路径风格",
	"split-path":                         "PowerShell 内置，拆分路径",

	// ===== 系统配置 =====
	"get-service | select": "筛选服务，配合 where-object 使用",
	"get-childitem env:":   "PowerShell 内置，列环境变量（替代 env）",
	"gci env:":             "同上别名",
	"$env:PATH":            "PowerShell 查看 PATH 变量",
	"system-properties":    "图形化系统属性",
	"control":              "打开控制面板",
	"msinfo32":             "系统信息（GUI 替代品，等价 systeminfo 详细版）",
	"dxdiag":               "DirectX 诊断，显示硬件详情（替代 hwinfo/lshw）",
	"msconfig":             "系统配置（启动项、服务），变更操作，沙箱禁止",
	"reg query":            "CMD 内置，查询注册表（替代 sysctl 部分功能）",
	"get-itemproperty":     "PowerShell 内置，读注册表项（替代 sysctl -a）",
	"gpupdate":             "组策略更新；变更操作，沙箱禁止",
	"gpresult":             "CMD 内置，查看组策略应用结果（仅 /r 报告模式）",
	"powercfg":             "电源配置；仅 /energy /batteryreport 等只读报告",
	"powercfg /energy":     "生成能效诊断报告（替代 powertop）",
	"bcdedit":              "启动配置；高危，沙箱严格禁用",

	// ===== 常用辅助 =====
	"cls":              "CMD 清屏",
	"clear":            "PowerShell 清屏",
	"exit":             "退出 shell",
	"logoff":           "CMD 内置，登出；高危，沙箱禁用",
	"shutdown":         "CMD 内置，关机/重启；高危，沙箱严格禁用（也在 DangerousPatterns 拦截）",
	"restart-computer": "PowerShell 重启；高危，沙箱严格禁用",
	"stop-computer":    "PowerShell 关机；高危",
	"history":          "PowerShell 历史命令（类似 bash history）",
	"get-history":      "PowerShell 内置，查看历史命令",
	"invoke-history":   "PowerShell 内置，重执行历史命令",
	"alias":            "PowerShell 内置，列出别名（替代 alias）",
	"get-alias":        "PowerShell 内置，列出别名",
	"gal":              "get-alias 别名",
	"measure-command":  "PowerShell 内置，统计命令执行时间（替代 time）",
	"swbemtest":        "WMI 测试工具（GUI）",
	"wbemtest":         "WMI 测试工具（GUI）",

	// ===== PowerShell 常用分析 cmdlet =====
	"get-process | sort cpu -desc":        "按 CPU 排序进程（替代 top）",
	"get-process | sort workingset -desc": "按内存排序进程",
	"get-process | group company":         "按发行商分组进程，排查可疑进程",
	"get-smbconnection":                   "查看 SMB 连接",
	"get-smbopenfile":                     "查看 SMB 打开的文件（替代 lsof）",
	"get-smb session":                     "查看 SMB 会话（替代 netstat）",
	"get-clipboard":                       "查看剪贴板",
	"set-clipboard":                       "设置剪贴板；变更，沙箱禁用",

	// ===== 计划任务（替代 crontab） =====
	"schtasks /query":   "CMD 内置，查询计划任务（替代 crontab -l）",
	"schtasks":          "沙箱内禁用变更操作，仅查询",
	"get-scheduledtask": "PowerShell 内置，查询计划任务",
}

// PlatformName 当前平台标识
const PlatformName = "windows"
