/*
 * Copyright 2025 CloudWeGo Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 */

package localcommand

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"sync"
)

// denybinLogPrefix denybin 相关日志前缀
const denybinLogPrefix = "[localcommand.denybin]"

// denybinLock 保护 denyBinDir 与 denyBinSetupOnce。
var denybinLock sync.Mutex
var denyBinDir string
var denyBinSetupOnce bool

// SetupDenyBin 在系统临时目录下创建 "denybin" 沙箱目录，里面放空 shim
// 覆盖一组 denylist 命令。然后把 denyBinDir 注入 PATH 最前端，使这些命令
// 在沙箱进程内"看似存在但拒绝执行"。
//
// 来源：OpenAI Codex Windows 沙箱设计
//
//	"在 PATH 最前端插入一个 denybin 目录，里面放空 shim"
//
// 与 SoftForbidden/字符串匹配的差异：
//   - 字符串匹配：检查命令字符串 → 误报率高
//   - denybin：真实二进制不可见 → 即便字符串检查漏了, shell 也找不到真实 binary
//
// 默认拒绝的命令（来自 PathACL.ExecDenied）：
//
//	curl / wget / nc / nmap / chmod / chown / setcap / dd / mkfs / fdisk / parted
//
// 调用方：Execute 主流程在执行前调用一次（SetupDenyBin 内部确保幂等）。
// 返回 denyBinDir 与注入后的 PATH。
func SetupDenyBin() (binDir string, newPATH string, err error) {
	denybinLock.Lock()
	defer denybinLock.Unlock()

	if denyBinSetupOnce {
		return denyBinDir, buildPathWithDenyBin(os.Getenv("PATH")), nil
	}

	// 1. 创建 denybin 临时目录
	tmpRoot := os.TempDir()
	binDir = filepath.Join(tmpRoot, fmt.Sprintf("yichouchou-denybin-%d", os.Getpid()))
	if err := os.RemoveAll(binDir); err != nil {
		return "", "", fmt.Errorf("clean denybin dir: %w", err)
	}
	if err := os.MkdirAll(binDir, 0o755); err != nil {
		return "", "", fmt.Errorf("mkdir denybin: %w", err)
	}

	// 2. 从 globalPathACL 读取 ExecDenied；为空时使用内置默认
	denied := defaultDeniedCommands()
	if acl := loadPathACL(); acl != nil && len(acl.ExecDenied) > 0 {
		denied = acl.ExecDenied
	}

	// 3. 为每个命令创建空 shim
	suffix := platformExeSuffix()
	for _, cmdName := range denied {
		if cmdName == "" {
			continue
		}
		shimPath := filepath.Join(binDir, cmdName+suffix)
		shimContent := buildDenyBinShim(cmdName)
		if err := os.WriteFile(shimPath, []byte(shimContent), 0o755); err != nil {
			return "", "", fmt.Errorf("write shim %s: %w", cmdName, err)
		}
	}

	denyBinDir = binDir
	denyBinSetupOnce = true
	newPATH = buildPathWithDenyBin(os.Getenv("PATH"))
	return binDir, newPATH, nil
}

// buildPathWithDenyBin 把 denyBinDir 插入到现有 PATH 最前端。
// 路径分隔符处理：Windows 用 `;`, Unix 用 `:`。
func buildPathWithDenyBin(oldPATH string) string {
	sep := string(os.PathListSeparator)
	if denyBinDir == "" {
		return oldPATH
	}
	if oldPATH == "" {
		return denyBinDir
	}
	return denyBinDir + sep + oldPATH
}

// buildDenyBinShim 生成 shim 文件内容（POSIX sh / Windows cmd 通用）。
//
// 任意命令被执行时, shim 输出拒绝信息并 exit 1。
func buildDenyBinShim(cmdName string) string {
	if runtime.GOOS == "windows" {
		// Windows: 用 .bat shim
		return fmt.Sprintf(`@echo off
echo [denybin] %s is forbidden in sandbox 1>&2
exit /b 1
`, cmdName)
	}
	// POSIX: 用 #!/bin/sh shim
	return fmt.Sprintf(`#!/bin/sh
# Auto-generated by yichouchou_claw denybin
# This shim blocks %q from executing in the sandbox.
echo "[denybin] %s is forbidden in sandbox" 1>&2
exit 1
`, cmdName, cmdName)
}

// platformExeSuffix 平台特定可执行后缀（Windows .exe/.bat）。
func platformExeSuffix() string {
	if runtime.GOOS == "windows" {
		return ".bat"
	}
	return ""
}

// defaultDeniedCommands 是兜底的 deny 命令列表。
//
// 来源：综合 OpenAI Codex + Linux capability 模型：
//   - 网络类：curl / wget / nc / nmap
//   - 权限修改类：chmod / chown / setcap
//   - 危险 IO 类：dd / mkfs / fdisk / parted
//
// 用户可通过 application.yml sandbox.exec_denied 自定义。
func defaultDeniedCommands() []string {
	return []string{
		// 网络
		"curl", "wget", "nc", "nmap",
		// 权限修改
		"chmod", "chown", "setcap", "setfattr",
		// 磁盘与分区
		"dd", "mkfs", "fdisk", "parted",
	}
}

// IsDenyBinPath 判断某路径是否就是 denybin 内的 shim。
// 用于调试和审计日志。
func IsDenyBinPath(path string) bool {
	if denyBinDir == "" {
		return false
	}
	abs1, _ := filepath.Abs(path)
	abs2, _ := filepath.Abs(denyBinDir)
	return abs1 == abs2 || strings.HasPrefix(abs1, abs2+string(filepath.Separator))
}

// 需要 fmt import
var _ = fmt.Sprintf
